version: "3.8"

services:
  my-monitor:
    image: nikhilvyamsani/my-monitor:latest
    container_name: my-monitor
    network_mode: "host"
    privileged: true
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: take_leap
      MYSQL_PORT: 3306
      MYSQL_HOST: localhost
      SITE_NAME: seekright
      ROOTFS: /host
      GF_LOG_LEVEL: info
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - /:/host:ro,rslave
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana-data:
