services:
  my-monitor:
    image: nikhilvyamsani/my-monitor:latest
    container_name: my-monitor
    ports:
      - "3000:3000"   # Grafana
      - "19090:9090"   # Prometheus
      - "8118:8118"   # Custom Python exporter
    environment:
      MYSQL_HOST: localhost  
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: take_leap
      MYSQL_PORT: 3306
      GF_LOG_LEVEL: debug
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana-data:
